services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minute-mate-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    develop:
      watch:
        - path: .
          target: /app
          action: sync
