services:
  mongodb:
    image: mongo:7
    container_name: minute-mate-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  backend:
    build: ./backend
    container_name: minute-mate-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: minute-mate-frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
